function submitForm() {
    document.getElementById('submitForm').submit();
}

let array;
let playerName;
let output = document.querySelector('#outputName');
const spinBtn = document.querySelector('#spinBtn');
const submitBtn = document.querySelector('#submitBtn');

function enableSubmit() {
    let names = document.getElementById('names');
    let isValid = true;

    for(var i=0; i<names.length; i++) {
        let changedNames = names[i];
        if(changedNames.value.trim() === '' || changedNames.value === null) {
            isValid = false;
            break;
        }
    }
    submitBtn.disabled = !isValid;
}


function setNames() {
    let names = document.getElementById('names').value;
    localStorage.setItem('names', names);
};

function getNames() {
    let names = localStorage.getItem('names');
    array = names.split(',');
    playerName = array[Math.floor(Math.random() * array.length)];
    console.log(playerName);
    output.textContent = `["${(playerName.toUpperCase()).trim()}"]`;
    tDoutput.textContent = `Choose 'Truth' or 'Dare'`;
};

const kidsTruth = ['What do you think your younger self would think of our relationship?',
'What have you learned about relationships from your parents?',
'When was the last time you cried?',
'Have your friendships taught you anything about romantic relationships?',
'What was the most surprising thing you learned about me?',
'When was the last time you laughed so much you cried?',
'In what ways do you think we\'re similar?',
'In what ways do you think we\'re different?',
'When have you felt most proud of me?',
'What makes you feel confident?',
'If we could travel anywhere together, where would we go?',
'What\'s your most treasured childhood memory?',
'What book, film, or TV show has had the greatest impact on you?',
'What excites you the most about life?',
'How important is a physical connection to you?',
'What do you think are the signs of a healthy relationship?',
'What is your favourite thing to do together?',
'Where do you feel most comfortable?',
'Is there something new you want to try together?',
'Do you have a favourite photograph of the two of us?',
'What value do you admire most about me?',
'Is affection in a relationship important to you? In what ways?',
'When you\'re feeling stressed, what\'s the best thing I can do for you?',
'Is there a song that reminds you of me?',
'Do you enjoy alone time? Why?',
'What do you think is the key to a happy, healthy relationship?',
'What would you change about yourself if you could?',
'If you could live anywhere, where would it be?',
'What is the best book you\'ve read?',
'What is the best gift you have been given?',
'What was the best phase in your life?',
'What was the worst phase in your life?',
'Are you more into looks or brains? Why?',
'How do you feel about sharing your password with your partner?',
'What kind of parent do you think you will be?',
'What would you do if your parents didn\'t like your partner?',
'Who is that one person you can talk to about just anything?',
'Have you ever lost someone close to you?',
'If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?',
'What do you think of best friends of the opposite sex?',
'Do you judge a book by its cover?',
'When was the last time you broke someone\'s heart?',
'What are you most thankful for?',
'Do you believe in second chances?',
'What\'s the one thing that people always misunderstand about you?',
'What did your past relationship teach you?',
'When have you felt your biggest adrenaline rush?',
'What is the craziest thing you\'ve ever done and would you do it again?',
'If a genie granted you 3 wishes right now, what would you wish for?',
'What\'s your biggest regret in life?',
'What do you think about when you\'re by yourself?',
'Why do you think you\'re single?',
'Who are five people you are closest with?',
'What\'s the most exciting thing that\'s happened this past year?',
'What was your longest relationship?',
'What food could you not live without?',
'What\'s one thing you wish you knew how to do?',
'Where\'s one place you\'d like to go that you haven\'t been?',
'What was the last book you read? And When?',
'What\'s the greatest risk you\'ve ever taken?',
'If you had the ability to erase something that you did in the past, what would it be?',
'What song makes you unconditionally happy?',
'If you could have anybody else\'s life, who\'s would you take?',
'What fictional character do you most relate to?',
'If you could take us anywhere in the world right now, where would you take us?',
'If you died tomorrow, what would you wish you had done?',
'Can you pin point the moment in your life where you were the happiest?',
'What song makes you unconditionally sad?',
'Have you ever seen something you can\'t explain?',
'If you could do one thing without suffering the consequences, what would you do?',
'What is the strangest dream you\'ve ever had?',
'What is the darkest thought you\'ve ever had?',
'What about the darkest thing you\'ve never told anybody?',
'Is there something out there, a thought, an idea, a current event, or a fear that you find deeply unsettling?',
'What would you consider to be your deepest fear?',
'Is there an activity that calms you? A place or a thing that makes you feel at ease?',
'What makes you feel uneasy? Overwhelmed? Anxious?',
'What scene in a movie has evoked the most feelings out of you?',
'What do you do or where do you go when you need to be alone?',
'What makes you feel like you need to be alone?',
'Can you remember a time in your life you felt the most alive? Tell me everything about that memory.',
'When have you felt the lowest in your life?',
'Where have you felt the most failure? The most success?',
'Tell me about the facts or harsh truths you choose to ignore but know you shouldn’t.',
'What is the biggest lie you ever told?',
'Where do you find meaning in your life?',
'Have you ever been in love? Tell me about the times you have been.',
'What did you do when you hurt someone the most?',
'If your life was a movie or a book what would be the title to it?',
'When have you caused the most harm to yourself?',
'What has been the biggest change you ever made that made you the most proud of yourself?',
'Is home for you a place or a feeling? Describe that place or describe that feeling.',
'What is your most cherished childhood memory?',
'Do you have any recurring dreams or nightmares?',
'If you could be given the date of your death would you want to know it?',
'Would you rather be loved or love?',
'How do you define beauty?',
'If you got a free cheque for $5,000 right this second, how would you use it?',
'What is the most romantic and loving thing you have ever done for somebody?',
'What is the most adventurous thing you have ever done in your life?'];

const kidsDare = ['Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your timeline\'s Instagram to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your timeline\'s Instagram to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your Instagram\'s timeline to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Text a random number and write “I see dead people”.',
'Let the rest of the group DM someone from your Instagram account.',
'Randomly call a person from your phone and sing them a song.',
'Prank call a friend\'s partner.',
'Talk about something you regret in your life.',
'Screenshot a picture of your browser history and send it to a random person in your contacts.',
'Hum, a random song, and you can\'t stop until someone guesses what it is.',
'Show everyone the four most recent pictures on your phone.',
'Hold your breath for as long as you can.',
'Ring a random person from your phone and confess that you\'re in love with a fictional character.',
'Allow another player to search for anything they want on your phone.',
'Tell everyone about an embarrassing crush you once had.',
'Tell the group why you are the best person in the world.',
'Tell everyone about a celebrity crush you have.',
'Act like you\'re a child for two minutes.'];

const adultsTruth = ['Are you scared of getting old?',
'At what age did you first taste alcohol?',
'At what age did you lose your virginity?',
'Boxers or briefs?',
'Do you believe in aliens?',
'Do you have a favorite child?',
'Do you secretly dislike any of your friends\' kids?',
'Do you still have feelings for any of your exes?',
'Have you ever been caught doing something you shouldn\'t have?',
'Have you ever been fired from a job?',
'Have you ever been in a fight?',
'Have you ever broken an expensive item?',
'Have you ever broken someone\'s heart?',
'Have you ever cheated on someone?',
'Have you ever compromised your morals for money? How?',
'Have you ever dated someone just for sex?',
'Have you ever flirted with a close friend\'s sibling?',
'Have you ever ghosted a friend?',
'Have you ever had a crush on a boss or teacher?',
'Have you ever had a crush on a coworker?',
'Have you ever had a crush on someone\'s parents?',
'Have you ever had a near-death experience?',
'Have you ever had your fortune told?',
'Have you ever re-gifted a present?',
'Have you ever said, “I love you” and not really meant it? To whom?',
'Have you ever stolen anything?',
'How do you really feel about your mother-in-law?',
'How many kids did (or do) you want to have?',
'How many people have you kissed?',
'How many secret admirers do you think you have in real life?',
'If I went through your cabinets, what\'s the weirdest thing I\'d find?',
'If you could be a fictional character for a day, who would you choose?',
'If you could be invisible, what\'s the first thing you would do?',
'If you could date two people at once, would you do it? If so, who?',
'If you could have a celebrity for a best friend, who would it be?',
'If you could hire someone to do one thing for you, what would it be?',
'If you could only accomplish three things in life, what would they be?',
'If you could only have one app on your phone what would it be?',
'If you could travel to the past and meet one person, who would it be?',
'If you had one week to live and you had to marry someone in this room, who would it be?',
'If you had to move to a different country tomorrow, where would you go?',
'If you had to only ever watch one genre of movies for the rest of your life, which would you choose?',
'If your house caught on fire and you could only save three things (besides people), what would they be?',
'Is there anyone in your life who you are jealous of?',
'Name one thing you\'d change about every person in this room.',
'Name one thing you\'d do if you knew there\'d be zero consequences.',
'Name someone you\'ve pretended to like but actually couldn\'t stand.',
'Personality-wise, are you more like your mom or your dad?',
'Tell us about the worst date you\'ve ever been on.',
'What app do you waste the most time on?',
'What are the top three things you look for in a love interest?',
'What are you most proud of in your life?',
'What bridges are you glad that you burned?',
'What celebrity do you think is overrated?',
'What do you want to be remembered for most in life?',
'What five things would you bring to a deserted island?',
'What is a secret you had as a child that you never told your parents?',
'What is a weird food that you love?',
'What is one thing you would stand in line an hour for?',
'What is one thing you\'d change about your appearance if you could?',
'What is that one thing you would never do for all the money in the world?',
'What is the biggest fight you\'ve ever been in with a friend?',
'What is the craziest pickup line you\'ve ever used?',
'What is the longest you\'ve ever gone without showering?',
'What is the worst food you\'ve ever tasted?',
'What is the worst physical pain you\'ve ever been in?',
'What is your biggest insecurity?',
'What is your greatest fear in a relationship?',
'What is your worst habit?',
'What song do you sing most in the shower?',
'What\'s best for you, a love marriage, marriage for money or arranged marriage?',
'What\'s one silly thing you can\'t live without?',
'What\'s something you\'re glad your mom doesn\'t know about you?',
'What\'s the biggest mistake you\'ve ever made?',
'What\'s the most trouble you\'ve been in?',
'What\'s the worst thing you\'ve ever said to anyone?',
'What\'s one job you could never do?',
'What\'s one useless skill you\'d love to learn anyway?',
'What\'s something you only do when you\'re alone?',
'What\'s the hardest drug you\'ve ever tried?',
'What\'s the last movie that made you cry?',
'What\'s the most common misconception about you?',
'What\'s the most ridiculous thing you have an emotional attachment to?',
'What\'s your worst memory from high school?',
'When is the last time you did something technically illegal?',
'When\'s the last time you apologized? What for?',
'When\'s the last time your partner embarrassed you?',
'Who would you bring with you on a deserted island?',
'Who would you call to help bury a body?',
'Would you date your high school crush today?'];

const adultsDare = ['Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your timeline\'s Instagram to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your timeline\'s Instagram to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Read the last text message you sent out loud.',
'Wear your clothes backwards for the rest of the game.',
'Put on a pair of underwear on your head for the rest of the game.',
'Eat a spoonful of hot sauce.',
'Lick a bar of soap.',
'Put on a blindfold and let someone feed you mystery food.',
'Try to lick your elbow.',
'Put on a blindfold and try to draw a picture of a dog.',
'Call your dad and ask him if he\'s proud of you.',
'Do a moonwalk.',
'Act out a scene from your favourite movie.',
'Put 3 ice cubes in your mouth and keep it there for 1 minute.',
'Call someone and try to sell them a pencil.',
'Make a prank call to your friend or family member.',
'Eat a spoonful of mustard.',
'Do an impression of a famous celebrity.',
'Eat a banana without using your hands.',
'Let another player pour a glass of water on your head.',
'Show the most embarrassing photo on your phone.',
'Try to drink a glass of water without using your hands.',
'Remove your socks with your teeth.',
'Act out a commercial for a product chosen by the other players.',
'Show the group your internet search history.',
'How old are you? Whatever your age is, do that many push-ups.',
'Let another player draw a washable marker mustache on you.',
'Call your crush.',
'Crack an egg on your head.',
'Dance like your life depends on it.',
'Talk without closing your mouth for 1 minute.',
'Do 5 minutes of stand-up comedy.',
'Say two honest things about everyone else in the group.',
'Dance with no music for 1 minute.',
'Message someone, you haven\'t talked to in a year.',
'Read aloud last 10 items in your search history.',
'Imitate a celebrity every time you talk.',
'Post the oldest selfie on your phone on Instagram Stories.',
'Using only your elbows, upload a WhatsApp status.',
'Text your crush and ask them out on a date.',
'Let another player post a status on your social media.',
'Do a plank for a minute.',
'Open your Instagram or Facebook and like each post of your ex or her sister.',
'Get in the weirdest yoga pose you\'ve ever done.',
'Show your most embarrassing photo on your phone.',
'Say something dirty to the person on your left.',
'Like the first 15 posts on your Instagram newsfeed.',
'Keep your eyes closed until it\'s your go again.',
'Pretend to be the person to your right for 10 minutes.',
'Try and make the group laugh as quickly as possible.',
'Tell everyone an embarrassing story about yourself.',
'Say everything in a whisper for the next 10 minutes.',
'Talk in an American accent till your next 3 turns.',
'Tell the saddest story you know.',
'Tell the group two truths and a lie, and they have to guess which one the lie is.',
'Reply to the first five Instagram Stories on your timeline.',
'Share the first celebrity on your Instagram\'s timeline to your Story.',
'Fill your mouth with drink and gargle your answer to the next Truth.',
'Smile as widely as you can and hold it for two minutes.',
'Sit on the floor for the rest of the game.',
'Give a personalised insult to everyone in the room.',
'Upload a story on your WhatsApp which says "engaged".',
'Sit in the corner of the room without speaking to anyone for the next 10 minutes.',
'Eat a whole raw clove of garlic.',
'Sing Despacito.',
'Read the last 5 text messages on your phone.',
'Pretend the person to your right is your girlfriend or boyfriend and beg them not to leave you.',
'Tell the funniest story of how you met someone in the group.',
'Call your friend and sign them Happy Birthday.',
'Pretend you\'re Forrest Gump and the person to your left as Jenny.',
'Pretend you\'re Jack and the person to your right Rose.',
'Sing the most romantic song you know.',
'Re-enact your favorite romantic scene from a movie.',
'Express your love with sign language.',
'Call a random number and pretend to be a different personality.',
'Find a random amount of trash and try to sell it to the group as if it is valuable.',
'Draw your favorite movie and have everyone try to guess it.',
'Talk like a robot until your next 2 turns.',
'Fill your mouth with water and try not to spit it out while the rest of the group cracks jokes.',
'Pretend to be a waiter or waitress and take food orders from everyone in the group.',
'Text a random number and write “I see dead people”.',
'Let the rest of the group DM someone from your Instagram account.',
'Randomly call a person from your phone and sing them a song.',
'Prank call a friend\'s partner.',
'Talk about something you regret in your life.',
'Screenshot a picture of your browser history and send it to a random person in your contacts.',
'Hum, a random song, and you can\'t stop until someone guesses what it is.',
'Show everyone the four most recent pictures on your phone.',
'Hold your breath for as long as you can.',
'Ring a random person from your phone and confess that you\'re in love with a fictional character.',
'Allow another player to search for anything they want on your phone.',
'Tell everyone about an embarrassing crush you once had.',
'Tell the group why you are the best person in the world.',
'Tell everyone about a celebrity crush you have.',
'Act like you\'re a child for two minutes.'];

// const ageGroup = document.getElementById()

const tDoutput = document.querySelector('#selectTD');
const qnOutput = document.querySelector('#truthDareQn');

const ageSelect = document.getElementById('ageSelect');

function setValue() {
    const selectedAge = ageSelect.value;
    localStorage.setItem('selectedValue', selectedAge);
    // window.location.href = 'gamePage.html';
};

function getTruthQn() {
    const selectedAge = localStorage.getItem('selectedValue');
    console.log(selectedAge);
    let adultsTruthQn = adultsTruth[Math.floor(Math.random() * adultsTruth.length)];
    let kidsTruthQn = kidsTruth[Math.floor(Math.random() * kidsTruth.length)];

    if(selectedAge === 'Adults') {
        qnOutput.textContent = `"${adultsTruthQn}"`;
    } else if (selectedAge === 'Kids') {
        qnOutput.textContent = `"${kidsTruthQn}"`;
    } else {
        qnOutput.textContent = `Go select 'Singles' or 'Couples'.`;
    }
}

function getDareQn() {
    const selectedAge = localStorage.getItem('selectedValue');
    console.log(selectedAge);
    let adultsDareQn = adultsDare[Math.floor(Math.random() * adultsDare.length)];
    let kidsDareQn = kidsDare[Math.floor(Math.random() * kidsDare.length)];

    if(selectedAge === 'Adults') {
        qnOutput.textContent = `"${adultsDareQn}"`;
    } else if (selectedAge === 'Kids') {
        qnOutput.textContent = `"${kidsDareQn}"`;
    } else {
        qnOutput.textContent = `Go select 'Singles' or 'Couples'.`;
    }
}

function playSpin() {
    let spin = document.querySelector('#player');
    spin.play();
}

function playTruthDare() {
    let truthOrDare = document.querySelector('#truthDare');
    truthOrDare.play();
}